on:
  workflow_dispatch:
  push:
    branches:
      main
  schedule:
    - cron:  '0 12 * * *'

name: Render-dev-Book

jobs:
  bookdown:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    name: Render-Book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 3
          extra-packages: local::.

      - name: Render book
        run: Rscript -e 'babelquarto::render_book()'
        env: # Set the secret as an input
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
          BABELQUARTO_CI_URL: https://devdevguide.netlify.app

      - name: Move English files
        run: Rscript -e 'file.copy(from = "_book/rOpenSci-Packages--Development,-Maintenance,-and-Peer-Review.pdf", to = "_book/ropensci-dev-guide.pdf")' -e 'purrr::walk(list.files("images", full.names = TRUE), file.copy, to = "_book/images")'

      - name: Move Spanish files
        run: Rscript -e 'file.copy(from = "_book/es/Paquetes-de-rOpenSci--Desarrollo,-mantenimiento-y-revisi√≥n-por-pares.pdf", to = "_book/es/ropensci-dev-guide.pdf")' -e 'purrr::walk(list.files("images", full.names = TRUE), file.copy, to = "_book/es/images")'

      - name: git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-pages committer"

      - name: Commit results
        env: # Set the secret as an input
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          cd _book
          git init
          git add .
          git commit -m 'update book'
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:dev-site --force
