on:
  release

name: Render-Book-from-master

jobs:
  bookdown:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render book html
        run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::bs4_book", params = list(AIRTABLE_API_KEY = ${{ secrets.AIRTABLE_API_KEY }}))'
        env: # Set the secret as an input
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}

      - name: Render book PDF
        run: Rscript -e 'bookdown::render_book("index.Rmd", new_session = FALSE, "bookdown::pdf_book", output_dir = "pdfbook", params = list(AIRTABLE_API_KEY = ${{ secrets.AIRTABLE_API_KEY }}))'
        env: # Set the secret as an input
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}

      - name: Move files around
        run: Rscript -e 'file.copy(from = "pdfbook/ropensci-dev-guide.pdf", to = "_book/ropensci-dev-guide.pdf")' -e 'purrr::walk(list.files("images", full.names = TRUE), file.copy, to = "_book/images")'

      - name: git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-pages committer"

      - name: Commit results
        run: |
          cp ghpagescname _book/CNAME
          cd _book
          git init
          git add .
          git commit -m 'update book'
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:gh-pages --force
